version: "3.8"
services:

  hashitaka:
    build: ./
    container_name: hashitaka
    volumes:
      - ./:/usr/src/app
      - hashitaka_node_modules:/usr/src/app/node_modules


volumes:
  hashitaka_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules